version: '3.1'

services:
  db:
    restart: always
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - DB_USER="postgres"
      - DB_PASS="postgres"
      - DB_NAME="elephant_in_the_room_dev"

  pgadmin4:
    image: fenglc/pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - 5050:5050
