version: '3.2'

services:
  db:
    container_name: elephant_in_the_room_db
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - DB_USER="postgres"
      - DB_PASS="postgres"
      - DB_NAME="elephant_in_the_room_dev"
    volumes:
      - elephant_in_the_room_db_data:/var/lib/postgresql/data

  pgadmin4:
    image: fenglc/pgadmin4
    depends_on:
      - db
    ports:
      - 5050:5050

volumes:
  elephant_in_the_room_db_data:
